spring:
  application:
    name: activemq
  activemq:
    user: user
    password: password
server:
  port: 8083
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true