spring:
  application:
    name: client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
broker:
  relay:
    host: ${BROKER_HOST:localhost}
---

spring:
  profiles: app1
#server:
#  port: 0

---

spring:
  profiles: app2
#server:
#  port: 0
