spring:
  application:
    name: activemq
  activemq:
    user: user
    password: password
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
broker:
  host: ${BROKER_HOST:localhost}
